filein = open("Exercise40-50\ex41\ex41_in.txt","r")
names = filein.readlines()
filein.close()
print(names)
names.sort()
amount = len(names)
fileout = open("Exercise40-50\ex41\ex41_out.txt","w+")
fileout.write("There are ")
fileout.write(str(amount))
fileout.write(" names:\n")
fileout.write("---------------------------\n")
fileout.writelines(names)
fileout.close()